name: Build and Deploy Valkyrie
on:
  push:
    branches:
      - main
      - valkyrie-qt5-qt6
      - test-workflow
  pull_request:
    branches:
      - main
      - valkyrie-qt5-qt6
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt-config:
          - version: '5.15.*'
            arch: gcc_64
            modules:
    steps:
      - id: install_qt
        name: Install Qt using GHA
        uses: jurplel/install-qt-action@v4
        with:
          arch: ${{ matrix.qt-config.arch }}
          version: ${{ matrix.qt-config.version }}
          modules: ${{ matrix.qt-config.modules }}
      - uses: actions/checkout@v4
      - id: compile_application
        name: Build application
        run: |
          mkdir build
          cd build
          qmake ..
          make  -j$(nproc)
      - id: upload-artifact
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-application
          path: build/
          
  get_latest_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest tag
      id: get_tag
      run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)
      
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: qt-application
        path: build/

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: build/**/*
        tag_name: ${{ steps.get_tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
