on:
  push:
    branches:
      - test-workflow
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - id: install_qt
        name: Install Qt using GHA
        uses: jurplel/install-qt-action@v4
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure
        run: | 
          mkdir -p $GITHUB_WORKSPACE/AppDir/usr
          qmake PREFIX=$GITHUB_WORKSPACE/AppDir/usr
      - name: Build
        run: | 
          make -j`nproc` install DESTDIR=$GITHUB_WORKSPACE/AppDir
          mkdir -p $GITHUB_WORKSPACE/AppDir/usr/share/icons/hicolor/256x256/apps
          cp -f $GITHUB_WORKSPACE/icons/valkyrie.png $GITHUB_WORKSPACE/AppDir/usr/share/icons/hicolor/256x256/apps
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|valkyrie|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./*.AppImage*
