on:
  push:
    branches:
      - test-workflow
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - id: install_qt
        name: Install Qt using GHA
        uses: jurplel/install-qt-action@v4
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2
          sudo apt-get install -y patchelf software-properties-common
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage
          sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder
      - name: Checkout code
        uses: actions/checkout@v4
      - name: configure
        run: qmake PREFIX=/usr
      - name: build
        run: make -j`nproc`
      - name: pack
        run: |
          sudo make install DESTDIR=AppDir
          export export UPDATE_INFO="gh-releases-zsync|AppImageCrafters|valkyrie|latest|*.AppImage.zsync"
          sudo appimage-builder --skip-test
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./*.AppImage*
